/* ケロちゃん みるみる in every language: [Tiếng Việt, English, 한국어] (see js/lang.js).
   ケロはかせ speaks Japanese with recorded clips (VOICEVOX:ずんだもん); in the other languages the phone reads
   these lines aloud (js/voice.js), so the lines he only says (never shown) are here too. */
Lang.add({
  // ---------------------------------------------------------------- title, menus
  'ケロちゃん みるみる': ['Kero Mắt Tinh', 'Kero Quick Eyes', '케로 반짝눈'],
  'だれが あそぶ？': ['Ai chơi nào?', 'Who is playing?', '누가 할래?'],
  'メニューに もどる': ['Về menu', 'Back to the menu', '메뉴로 돌아가기'],
  'ホームに ついか': ['Thêm vào màn hình', 'Add to Home', '홈 화면에 추가'],
  'こえ': ['Giọng nói', 'Voice', '목소리'],
  'こうかおん': ['Âm thanh', 'Sound effects', '효과음'],
  'おんがく': ['Nhạc', 'Music', '음악'],
  'きょうの めチェック': ['Kiểm tra mắt hôm nay', "Today's Eye Check", '오늘의 눈 체크'],
  'めチェック': ['Kiểm tra mắt', 'Eye Check', '눈 체크'],
  'できた': ['Xong', 'Done', '완료'],
  'トレーニング': ['Luyện tập', 'Training', '트레이닝'],
  'ストレッチ': ['Thể dục mắt', 'Eye Stretch', '눈 스트레칭'],
  'スタンプ': ['Con dấu', 'Stamps', '도장'],
  'きろく': ['Kỷ lục', 'Records', '기록'],
  'まめちしき': ['Điều thú vị', 'Eye Facts', '눈 상식'],
  'おみせ': ['Cửa hàng', 'Shop', '가게'],
  'もどる': ['Quay lại', 'Back', '뒤로'],
  'やめる': ['Thôi', 'Stop', '그만'],
  'とじる': ['Đóng', 'Close', '닫기'],
  'つぎへ': ['Tiếp theo', 'Next', '다음'],
  'もういちど': ['Chơi lại', 'Again', '다시 하기'],
  'まえの つき': ['Tháng trước', 'Previous month', '이전 달'],
  'つぎの つき': ['Tháng sau', 'Next month', '다음 달'],
  'なまえなし': ['Chưa có tên', 'No name', '이름 없음'],
  'こえ：{credit}': ['Giọng nói: {credit}', 'Voice: {credit}', '목소리: {credit}'],
  '日本語の こえ：{credit}': ['Giọng tiếng Nhật: {credit}', 'Japanese voice: {credit}', '일본어 목소리: {credit}'],
  'おとな': ['Người lớn', 'Grown-up', '어른'],
  'こども': ['Trẻ em', 'Child', '어린이'],
  '{name}、': ['{name} ơi, ', '{name}, ', '{name}, '],
  'ケロはかせ「{t}」': ['Giáo sư Kero: “{t}”', 'Dr. Kero: “{t}”', '케로 박사: “{t}”'],
  '（{t}）': [' ({t})', ' ({t})', ' ({t})'],
  '？': ['?', '?', '?'],

  // ---------------------------------------------------------------- the list and a training's page
  'うごきを みる': ['Nhìn vật chuyển động', 'Moving Things', '움직임 보기'],
  '動体視力': ['Thị lực động', 'Dynamic vision', '동체 시력'],
  'いっしゅんで みる': ['Nhìn trong chớp mắt', 'In a Flash', '한순간에 보기'],
  '瞬間視': ['Nhìn tức thời', 'Instant vision', '순간 시력'],
  'めを うごかす': ['Đảo mắt thật nhanh', 'Moving Your Eyes', '눈 움직이기'],
  '眼球運動': ['Vận động nhãn cầu', 'Eye movement', '안구 운동'],
  'まわりを みる': ['Nhìn xung quanh', 'Looking Around', '주변 보기'],
  '周辺視野': ['Tầm nhìn ngoại vi', 'Peripheral vision', '주변 시야'],
  'みて タッチ': ['Nhìn rồi chạm', 'See & Tap', '보고 터치'],
  '眼と手の協応': ['Phối hợp mắt và tay', 'Eye-hand coordination', '눈과 손의 협응'],
  'スポーツ': ['Thể thao', 'Sports', '스포츠'],
  'スタンプ あと {n}こ': ['Còn {n} con dấu', '{n} more stamps', '도장 {n}개 더'],
  'あたらしい': ['Mới', 'New', '새로'],
  'おすすめ': ['Gợi ý', 'Try this', '추천'],
  'れんしゅう': ['Luyện tập', 'Practice', '연습'],
  'はじめる': ['Bắt đầu', 'Start', '시작'],
  'いちばん：{best}': ['Tốt nhất: {best}', 'Best: {best}', '최고: {best}'],
  '「{level}」は「{from}」で {animal} いじょう か、スタンプ {n}こで あくよ': ['Mức “{level}” sẽ mở khi đạt {animal} trở lên ở mức “{from}”, hoặc có {n} con dấu', '“{level}” opens with {animal} or better at “{from}”, or with {n} stamps', '「{level}」은 「{from}」에서 {animal} 이상이거나 도장 {n}개면 열려'],
  'きろくに ちょうせん': ['Thử thách kỷ lục', 'Record Challenge', '기록 도전'],
  'きろくに ちょうせん（さいこう {n}）': ['Thử thách kỷ lục (cao nhất {n})', 'Record Challenge (best {n})', '기록 도전 (최고 {n})'],
  'スタート！': ['Bắt đầu!', 'Go!', '시작!'],
  'けす': ['Xóa', 'Del', '지우기'],
  'チェック': ['Kiểm tra', 'Check', '체크'],
  'かんたん': ['Dễ', 'Easy', '쉬움'],
  'ふつう': ['Vừa', 'Normal', '보통'],
  'むずかしい': ['Khó', 'Hard', '어려움'],
  'おとな かんたん': ['Người lớn · Dễ', 'Grown-up · Easy', '어른 · 쉬움'],
  'おとな ふつう': ['Người lớn · Vừa', 'Grown-up · Normal', '어른 · 보통'],
  'おとな むずかしい': ['Người lớn · Khó', 'Grown-up · Hard', '어른 · 어려움'],
  'ちょっと おやすみ': ['Nghỉ một chút', 'Taking a break', '잠깐 쉬어'],
  'つづける': ['Chơi tiếp', 'Continue', '계속하기'],

  // ---------------------------------------------------------------- the trainings: names and how to play
  'シャッフル': ['Tráo cốc', 'Cup Shuffle', '컵 섞기'],
  'かぞえて びゅん': ['Đếm vèo vèo', 'Zoom Count', '휙휙 세기'],
  'ぱっと すうじ': ['Số chớp nhoáng', 'Flash Number', '반짝 숫자'],
  'ぱっと まる': ['Tìm hình tròn', 'Flash Circle', '반짝 동그라미'],
  'トリプル C': ['Ba chữ C', 'Triple C', '트리플 C'],
  'かぞえて C': ['Đếm chữ C', 'Count the C', 'C 세기'],
  'まわりの C': ['Chữ C xung quanh', 'Around C', '주변의 C'],
  'うえした C': ['Chữ C trên dưới', 'Up-Down C', '위아래 C'],
  'れんぞく タッチ': ['Chạm liên tục', 'Quick Touch', '연속 터치'],
  'ナンバー タッチ': ['Chạm số', 'Number Touch', '숫자 터치'],
  'やきゅう': ['Bóng chày', 'Baseball', '야구'],
  'ボクシング': ['Quyền anh', 'Boxing', '복싱'],
  'たっきゅう': ['Bóng bàn', 'Table Tennis', '탁구'],
  'バスケット': ['Bóng rổ', 'Basketball', '농구'],
  'バレー': ['Bóng chuyền', 'Volleyball', '배구'],
  'サッカー': ['Bóng đá', 'Soccer', '축구'],
  'アメフト': ['Bóng bầu dục', 'American Football', '미식축구'],
  'コップの どれかに ひよこが いるよ。\nコップが いれかわるのを めで おいかけて、\nひよこが いる コップを タッチしてね！': ['Có một chú gà con trốn dưới một cái cốc.\nHãy dõi mắt theo các cốc khi chúng đổi chỗ,\nrồi chạm vào cốc có gà con nhé!', 'A chick is hiding under one of the cups.\nFollow the cups with your eyes as they swap,\nthen tap the cup with the chick!', '컵 중 하나에 병아리가 있어.\n컵이 바뀌는 걸 눈으로 따라가서\n병아리가 있는 컵을 터치해!'],
  'さいしょに でた えと おなじ えが、\nよこに びゅんと ながれるよ。\nいくつ あったか かぞえてね！': ['Những hình giống hình lúc đầu\nsẽ bay vèo qua màn hình.\nĐếm xem có mấy hình nhé!', 'Pictures zoom across the screen.\nCount how many are the same\nas the first picture!', '처음 나온 그림과 같은 그림이\n옆으로 휙 지나가.\n몇 개였는지 세어 봐!'],
  'すうじが いっしゅんだけ でるよ。\nなんの すうじ だったか こたえてね！': ['Một con số hiện ra trong chớp mắt.\nĐó là số mấy nhỉ?', 'A number flashes for a moment.\nWhat number was it?', '숫자가 한순간만 나와.\n무슨 숫자였는지 맞혀 봐!'],
  'いろいろな マークが いっしゅん でるよ。\n○が あった ばしょを タッチしてね！': ['Nhiều hình hiện ra trong chớp mắt.\nChạm vào chỗ có hình tròn ○ nhé!', 'Lots of shapes flash for a moment.\nTap where the circle ○ was!', '여러 가지 모양이 한순간 나와.\n○가 있던 곳을 터치해!'],
  'いろいろな ばしょに「C」が でるよ。\nでた じゅんばんに、Cの あいてる ほう\n（↑ → ↓ ←）を こたえてね！': ['Chữ “C” hiện ra ở nhiều chỗ khác nhau.\nTheo đúng thứ tự, hãy chọn phía\nchữ C mở ra (↑ → ↓ ←) nhé!', 'A “C” pops up in different places.\nIn the same order, answer which way\neach C was open (↑ → ↓ ←)!', '여러 곳에 「C」가 나와.\n나온 순서대로 C가 열린 쪽\n(↑ → ↓ ←)을 골라 봐!'],
  'さいしょに でた Cと おなじ むきの Cが\nいくつ でたか かぞえてね！': ['Đếm xem có bao nhiêu chữ C\nquay cùng hướng với chữ C đầu tiên nhé!', 'Count how many Cs face the same way\nas the first C!', '처음 나온 C와 같은 방향의 C가\n몇 개 나왔는지 세어 봐!'],
  'まんなかの「C」と おなじ むきの Cを\nまわりから さがして タッチしてね！\nはやさを はかるよ': ['Tìm ở xung quanh chữ C quay cùng hướng\nvới chữ “C” ở giữa, rồi chạm vào nhé!\nCó bấm giờ đó', 'Find the C around the edge that faces\nthe same way as the “C” in the middle, and tap it!\nWe time how fast you are', '가운데 「C」와 같은 방향의 C를\n주변에서 찾아서 터치해!\n빠르기를 재'],
  'まんなかの ほしを みていてね。\nうえと したに「C」が いっしゅん でるよ。\nおなじ むきか ちがう むきか こたえてね！': ['Nhìn vào ngôi sao ở giữa nhé.\nHai chữ “C” hiện ra ở trên và dưới trong chớp mắt.\nChúng cùng hướng hay khác hướng?', 'Keep looking at the star in the middle.\nTwo “C”s flash at the top and bottom.\nDo they face the same way or not?', '가운데 별을 보고 있어.\n위와 아래에 「C」가 한순간 나와.\n같은 방향인지 다른 방향인지 맞혀 봐!'],
  'あちこちに しかくが でては きえるよ。\nきえる まえに すばやく タッチしてね！': ['Các ô vuông hiện ra rồi biến mất khắp nơi.\nChạm thật nhanh trước khi chúng biến mất nhé!', 'Squares pop up here and there and vanish.\nTap each one quickly before it is gone!', '여기저기 네모가 나왔다 사라져.\n사라지기 전에 빨리 터치해!'],
  'すうじの パネルを、1から じゅんばんに\nできるだけ はやく タッチしてね！': ['Chạm vào các ô số theo thứ tự từ 1\nthật nhanh nhé!', 'Tap the number panels in order from 1,\nas fast as you can!', '숫자 판을 1부터 차례로\n최대한 빨리 터치해!'],
  'ピッチャーが ボールを なげるよ。\nボールが ホームに きた ときに\nタッチして うちかえそう！': ['Người ném bóng sẽ ném bóng tới.\nKhi bóng bay tới chỗ mình,\nchạm để đánh bóng nhé!', 'The pitcher throws the ball.\nWhen the ball reaches home plate,\ntap to hit it!', '투수가 공을 던져.\n공이 홈에 왔을 때\n터치해서 쳐 봐!'],
  'トレーナーが だす ミットを\nすばやく タッチしよう！\nパンチが きたら やじるしの ほうへ\nゆびを スライドして よけてね': ['Chạm thật nhanh vào găng đích\nmà huấn luyện viên đưa ra!\nKhi có cú đấm, vuốt ngón tay\ntheo mũi tên để né nhé', 'Quickly tap the mitt\nthe trainer holds up!\nWhen a punch comes, slide your finger\nthe way the arrow points to dodge', '트레이너가 내미는 미트를\n빨리 터치해!\n펀치가 오면 화살표 쪽으로\n손가락을 밀어서 피해'],
  'あいてが うった ボールが とんで くるよ。\nてまえに きた ボールを タッチして\nうちかえそう！ ラリーを つづけてね': ['Bạn bên kia đánh bóng sang.\nKhi bóng tới gần, chạm vào bóng\nđể đánh trả! Giữ đường bóng thật lâu nhé', 'The ball comes flying over the net.\nTap it when it reaches your end\nto hit it back! Keep the rally going', '상대가 친 공이 날아와.\n앞으로 온 공을 터치해서\n받아쳐! 랠리를 이어 가'],
  'せんしゅが はしって くるよ。\nみどりの ふくが みかた、オレンジが あいて。\nかげに なったら、みかたを タッチしてね！': ['Các cầu thủ chạy vào sân.\nÁo xanh lá là đội mình, áo cam là đội bạn.\nKhi họ thành bóng đen, chạm vào đội mình nhé!', 'Players run onto the court.\nGreen shirts are your team, orange the other team.\nWhen they turn into shadows, tap your teammates!', '선수들이 달려와.\n초록 옷이 우리 편, 주황 옷이 상대 편.\n그림자가 되면 우리 편을 터치해!'],
  'みかたが ボールを あげるよ。\nボールが たかい ところ（しろい おび）に\nきたら タッチして スパイク！': ['Đồng đội tung bóng lên.\nKhi bóng lên cao (tới dải màu trắng),\nchạm vào để đập bóng!', 'Your teammate sets the ball up.\nWhen it is high up (in the white band),\ntap it to spike!', '우리 편이 공을 올려 줘.\n공이 높은 곳(하얀 띠)에\n오면 터치해서 스파이크!'],
  'あかい あいてが じゃまを しているよ。\nじゃまされて いない みかた（みどり）へ\nボールから ゆびを スライドして パス！': ['Đội bạn áo đỏ đang chặn đường.\nVuốt từ quả bóng về phía đồng đội\n(áo xanh lá) không bị chặn để chuyền!', 'The red team is in the way.\nSlide from the ball towards the teammate\n(green) nobody is blocking to pass!', '빨간 상대가 막고 있어.\n막히지 않은 우리 편(초록)에게\n공에서 손가락을 밀어서 패스!'],
  'ボールを もって はしるよ。\nあいてが つっこんで くるから、\nひだりか みぎを タッチして よけてね！': ['Ôm bóng chạy thật nhanh nào.\nĐội bạn lao tới, hãy chạm\nbên trái hoặc bên phải để né nhé!', 'Run with the ball!\nThe other team rushes at you:\ntap left or right to dodge!', '공을 들고 달려.\n상대가 돌진해 오니까\n왼쪽이나 오른쪽을 터치해서 피해!'],

  // ---------------------------------------------------------------- inside the trainings
  'ひよこを よく みててね！': ['Nhìn kỹ chú gà con nhé!', 'Watch the chick!', '병아리를 잘 봐!'],
  'めで おいかけて！': ['Dõi mắt theo nhé!', 'Follow with your eyes!', '눈으로 따라가!'],
  'ひよこは どこ？': ['Gà con ở đâu?', 'Where is the chick?', '병아리는 어디?'],
  'この えを かぞえてね！': ['Đếm hình này nhé!', 'Count this picture!', '이 그림을 세어 봐!'],
  'いくつ あった？': ['Có mấy cái?', 'How many?', '몇 개였어?'],
  'いくつ でるかな？': ['Sẽ có mấy cái nhỉ?', 'How many will come?', '몇 개 나올까?'],
  'こたえは {n}': ['Đáp án: {n}', 'The answer is {n}', '정답은 {n}'],
  'すうじが ぱっと でるよ': ['Một con số sắp hiện ra', 'A number is coming', '숫자가 반짝 나와'],
  'なんだった？': ['Là số mấy?', 'What was it?', '뭐였어?'],
  'マークが ぱっと でるよ': ['Các hình sắp hiện ra', 'Shapes are coming', '모양이 반짝 나와'],
  '○は どこに あった？': ['Hình tròn ○ ở đâu?', 'Where was the ○?', '○는 어디 있었어?'],
  'Cが {n}かい でるよ': ['Chữ C sẽ hiện ra {n} lần', 'A C will appear {n} times', 'C가 {n}번 나와'],
  'Cの あいてる ほうを おぼえてね': ['Nhớ phía chữ C mở ra nhé', 'Remember which way each C opens', 'C가 열린 쪽을 기억해'],
  'でた じゅんに こたえてね': ['Trả lời theo đúng thứ tự nhé', 'Answer in the same order', '나온 순서대로 대답해'],
  'ぜんぶ あたり！': ['Đúng hết!', 'All right!', '전부 정답!'],
  'こたえは これ': ['Đáp án là đây', 'Here is the answer', '정답은 이거야'],
  'この むきの Cを かぞえてね！': ['Đếm chữ C quay hướng này nhé!', 'Count the Cs facing this way!', '이 방향의 C를 세어 봐!'],
  'おなじ むきは いくつ？': ['Có mấy chữ C cùng hướng?', 'How many face the same way?', '같은 방향은 몇 개?'],
  'まんなかと おなじ むきの Cは どれ？': ['Chữ C nào cùng hướng với chữ ở giữa?', 'Which C faces like the middle one?', '가운데와 같은 방향의 C는?'],
  'おなじ': ['Giống', 'Same', '같아'],
  'ちがう': ['Khác', 'Different', '달라'],
  'おなじ むき だった？': ['Có cùng hướng không?', 'The same way?', '같은 방향이었어?'],
  'まんなかの ほしを みててね': ['Nhìn ngôi sao ở giữa nhé', 'Look at the star in the middle', '가운데 별을 봐'],
  'きえる まえに タッチ！': ['Chạm trước khi biến mất!', 'Tap before it vanishes!', '사라지기 전에 터치!'],
  'できた！': ['Xong rồi!', 'Done!', '다 했다!'],
  'つぎは {n}': ['Tiếp theo: {n}', 'Next: {n}', '다음은 {n}'],
  'ホームラン！': ['Home run!', 'Home run!', '홈런!'],
  'ヒット！': ['Trúng rồi!', 'Hit!', '안타!'],
  'からぶり': ['Trượt rồi', 'Missed', '헛스윙'],
  'ストライク': ['Bóng qua rồi', 'Strike', '스트라이크'],
  'ボールが きたら タッチ！': ['Bóng tới thì chạm!', 'Tap when the ball comes!', '공이 오면 터치!'],
  'パン！': ['Bụp!', 'Pow!', '팡!'],
  'よけた！': ['Né được rồi!', 'Dodged!', '피했다!'],
  'いたっ！': ['Ui da!', 'Ouch!', '아야!'],
  'おそい！': ['Chậm rồi!', 'Too slow!', '늦었어!'],
  'よけて！': ['Né đi!', 'Dodge!', '피해!'],
  'ミットを タッチ！': ['Chạm vào găng!', 'Tap the mitt!', '미트를 터치!'],
  'ナイス！': ['Hay lắm!', 'Nice!', '나이스!'],
  'ミス！': ['Hụt rồi!', 'Miss!', '놓쳤다!'],
  'ラリー {n}': ['Đường bóng {n}', 'Rally {n}', '랠리 {n}'],
  'ボールを タッチして うちかえそう': ['Chạm bóng để đánh trả nhé', 'Tap the ball to hit it back', '공을 터치해서 받아치자'],
  'みかた（みどり）は どこ？': ['Đội mình (xanh lá) ở đâu?', 'Where is your team (green)?', '우리 편(초록)은 어디?'],
  'みどりの ふくが みかた だよ': ['Áo xanh lá là đội mình', 'Green shirts are your team', '초록 옷이 우리 편이야'],
  'スパイク！': ['Đập bóng!', 'Spike!', '스파이크!'],
  'たかい ところで タッチ！': ['Chạm khi bóng ở trên cao!', 'Tap it up high!', '높은 곳에서 터치!'],
  'そとへ…': ['Ra ngoài rồi…', 'Out…', '밖으로…'],
  'ナイスパス！': ['Chuyền hay lắm!', 'Nice pass!', '나이스 패스!'],
  'とられた！': ['Bị cướp bóng rồi!', 'Stolen!', '뺏겼다!'],
  'フリーの みかたに パス！': ['Chuyền cho đồng đội không bị chặn!', 'Pass to the free teammate!', '비어 있는 우리 편에게 패스!'],
  'タックル！': ['Bị cản rồi!', 'Tackled!', '태클!'],
  'ひだりか みぎを タッチして よけよう': ['Chạm bên trái hoặc phải để né', 'Tap left or right to dodge', '왼쪽이나 오른쪽을 터치해서 피하자'],

  // ---------------------------------------------------------------- results
  '{s}びょう': ['{s} giây', '{s} s', '{s}초'],
  '・まちがい {n}': [' · sai {n}', ' · {n} wrong', ' · 실수 {n}'],
  '{a}もん せいかい（{b}もん）': ['Đúng {a}/{b} câu', '{a} of {b} right', '{b}문제 중 {a}개 정답'],
  '{a} / {b} せいこう': ['Thành công {a}/{b}', '{a} of {b} made', '{b}번 중 {a}번 성공'],
  'つづけて {a}かい': ['Liên tiếp {a} lần', '{a} in a row', '연속 {a}번'],
  'リストへ': ['Danh sách', 'List', '목록으로'],
  '{animal}！': ['{animal}!', '{animal}!', '{animal}!'],
  'じこベスト！': ['Kỷ lục mới!', 'Personal best!', '자기 최고!'],
  'いちばん：{n}かい': ['Tốt nhất: {n} lần', 'Best: {n}', '최고: {n}번'],
  '{n}かい！': ['{n} lần!', '{n}!', '{n}번!'],
  'しんきろく！': ['Kỷ lục mới!', 'New record!', '신기록!'],
  'もぐら': ['Chuột chũi', 'Mole', '두더지'],
  'いぬ': ['Chó', 'Dog', '강아지'],
  'ねこ': ['Mèo', 'Cat', '고양이'],
  'ふくろう': ['Cú mèo', 'Owl', '부엉이'],
  'カメレオン': ['Tắc kè hoa', 'Chameleon', '카멜레온'],
  'トンボ': ['Chuồn chuồn', 'Dragonfly', '잠자리'],
  'わし': ['Đại bàng', 'Eagle', '독수리'],
  'もぐらは つちの なかで くらすから、あかるいか くらいかが わかる くらい なんだって': ['Chuột chũi sống dưới đất, nên nghe nói chỉ phân biệt được sáng hay tối thôi', 'Moles live under the ground, so they can only tell light from dark', '두더지는 땅속에서 살아서 밝은지 어두운지만 안대'],
  'いぬは うごいて いる ものを みつけるのが とくい だよ': ['Chó rất giỏi phát hiện những thứ đang chuyển động', 'Dogs are good at spotting things that move', '강아지는 움직이는 걸 찾는 게 특기야'],
  'ねこは くらい ところでも よく みえるよ': ['Mèo nhìn rõ cả trong bóng tối', 'Cats see well even in the dark', '고양이는 어두운 곳에서도 잘 보여'],
  'ふくろうは よるでも えものを みつけられるよ': ['Cú mèo tìm được con mồi cả vào ban đêm', 'Owls can find their food even at night', '부엉이는 밤에도 먹이를 찾을 수 있어'],
  'カメレオンは みぎと ひだりの めを べつべつに うごかせるよ': ['Tắc kè hoa đảo được mắt trái và mắt phải riêng rẽ', 'Chameleons can move their left and right eyes separately', '카멜레온은 오른쪽 눈과 왼쪽 눈을 따로따로 움직일 수 있어'],
  'トンボは まわりが ぐるっと ぜんぶ みえるんだって': ['Nghe nói chuồn chuồn nhìn được hết một vòng xung quanh', 'Dragonflies can see all the way around them', '잠자리는 주위를 빙 둘러 다 볼 수 있대'],
  'わしは たかい そらから じめんの ちいさな どうぶつも みつけられるよ': ['Đại bàng nhìn thấy cả con vật nhỏ dưới đất từ trên trời cao', 'Eagles can spot small animals on the ground from high in the sky', '독수리는 높은 하늘에서 땅 위의 작은 동물도 찾을 수 있어'],

  // ---------------------------------------------------------------- ケロはかせ's lines
  'おはよう！': ['Chào buổi sáng!', 'Good morning!', '좋은 아침!'],
  'こんにちは！': ['Xin chào!', 'Hello!', '안녕!'],
  'こんばんは！': ['Chào buổi tối!', 'Good evening!', '좋은 저녁이야!'],
  'きょうも めの たいそう しよう！': ['Hôm nay mình cùng tập thể dục cho mắt nào!', "Let's exercise our eyes today!", '오늘도 눈 체조 하자!'],
  'まいにち すこしずつ やると めぢからが ぐんぐん つくよ': ['Mỗi ngày tập một chút, mắt sẽ tinh hơn nhiều đó', 'A little every day makes your eyes sharper and sharper!', '매일 조금씩 하면 눈의 힘이 쑥쑥 자라!'],
  'どの トレーニングに する？': ['Hôm nay chơi bài nào?', 'Which training shall we do?', '어떤 트레이닝 할래?'],
  'はじめまして！ ケロはかせ だよ。まいにち いっしょに めの たいそう しようね！': ['Chào bạn! Tớ là Giáo sư Kero. Mỗi ngày cùng tớ tập thể dục cho mắt nhé!', "Nice to meet you! I'm Dr. Kero. Let's exercise our eyes together every day!", '반가워! 난 케로 박사야. 매일 같이 눈 체조 하자!'],
  'まずは きょうの めチェックから やってみる？': ['Trước tiên, thử kiểm tra mắt hôm nay nhé?', "Shall we start with today's eye check?", '먼저 오늘의 눈 체크부터 해 볼까?'],
  'きょうは たくさん がんばったね！ めを やすめて、つづきは また あした！': ['Hôm nay cố gắng nhiều rồi! Cho mắt nghỉ ngơi, mai chơi tiếp nhé!', 'You worked hard today! Rest your eyes, and more tomorrow!', '오늘 정말 열심히 했어! 눈을 쉬게 하고 내일 또 하자!'],
  'あたらしい トレーニングが ふえたよ！': ['Có bài luyện tập mới rồi!', 'A new training is here!', '새 트레이닝이 생겼어!'],
  '「むずかしい」で あそべるように なったよ！': ['Giờ chơi được mức “Khó” rồi!', 'Now you can play “Hard”!', '이제 「어려움」으로 할 수 있어!'],
  'すごい！ いままでで いちばんだよ！': ['Tuyệt quá! Tốt nhất từ trước tới giờ!', 'Wow! Your best ever!', '대단해! 지금까지 중 최고야!'],
  'じこベスト！ やったね！': ['Kỷ lục mới! Giỏi quá!', 'A new personal best! Yay!', '자기 최고 기록! 해냈다!'],
  'はじめての きろく だね！': ['Kỷ lục đầu tiên đó!', 'Your first record!', '첫 기록이야!'],
  'よく できました！': ['Giỏi lắm!', 'Well done!', '잘했어!'],
  'いい ちょうし！': ['Đang tốt lắm!', "You're doing great!", '좋은 흐름이야!'],
  'がんばったね！': ['Cố gắng lắm!', 'Good effort!', '열심히 했구나!'],
  'すばらしい！': ['Tuyệt vời!', 'Wonderful!', '훌륭해!'],
  'だいじょうぶ！ ゆっくりで いいよ': ['Không sao! Cứ từ từ nhé', "It's OK! Take your time", '괜찮아! 천천히 해도 돼'],
  'つぎは もっと できるよ！': ['Lần sau sẽ làm tốt hơn!', "You'll do even better next time!", '다음엔 더 잘할 수 있어!'],
  'まいにち やると ぐんぐん のびるよ': ['Chơi mỗi ngày là tiến bộ nhanh lắm', "Play every day and you'll grow fast!", '매일 하면 쑥쑥 늘어!'],
  'はじめてなら「れんしゅう」で ためせるよ': ['Lần đầu thì thử ở “Luyện tập” trước nhé', 'First time? You can try it in “Practice”', '처음이면 「연습」으로 해 볼 수 있어'],
  'じょうず！ こんどは ほんとうに やってみよう！': ['Giỏi lắm! Giờ mình chơi thật nhé!', "Well done! Now let's do it for real!", '잘했어! 이제 진짜로 해 보자!'],
  'スタンプを あつめると あそべるよ': ['Sưu tầm con dấu là chơi được nhé', 'Collect stamps to play this', '도장을 모으면 할 수 있어'],
  'ケロはかせが しゃべるよ！': ['Giáo sư Kero sẽ nói nhé!', 'Dr. Kero will talk!', '케로 박사가 말할게!'],
  'きょうの めの まめちしき！': ['Điều thú vị về mắt hôm nay!', "Today's eye fact!", '오늘의 눈 상식!'],
  'しんきろく！ すごい！': ['Kỷ lục mới! Giỏi quá!', 'A new record! Amazing!', '신기록! 대단해!'],

  // ---------------------------------------------------------------- overlays
  'やったね！': ['Làm được rồi!', 'You did it!', '해냈다!'],
  'はなまる スタンプ！': ['Con dấu bông hoa!', 'Flower stamp!', '꽃 도장!'],
  'スタンプ ゲット！': ['Được con dấu!', 'You got a stamp!', '도장 획득!'],
  'スタンプ {n}こめ！': ['Con dấu thứ {n}!', 'Stamp No. {n}!', '{n}번째 도장!'],
  'あたらしい トレーニング！': ['Bài luyện tập mới!', 'New training!', '새 트레이닝!'],
  '「{name}」で あそべるよ': ['Giờ chơi được “{name}” rồi', 'You can play “{name}” now', '이제 「{name}」 할 수 있어'],
  '「むずかしい」が あそべるよ！': ['Đã chơi được mức “Khó”!', 'You can play “Hard” now!', '「어려움」을 할 수 있어!'],
  '「{name}」で「{level}」が えらべるよ': ['Giờ chọn được mức “{level}” ở “{name}”', 'You can choose “{level}” in “{name}”', '「{name}」에서 「{level}」을 고를 수 있어'],
  'ぜんぶの トレーニングで「むずかしい」が えらべるよ': ['Giờ bài nào cũng chọn được mức “Khó”', 'You can choose “Hard” in every training', '모든 트레이닝에서 「어려움」을 고를 수 있어'],
  'めの まめちしき No.{n}': ['Điều thú vị về mắt số {n}', 'Eye Fact No. {n}', '눈 상식 No.{n}'],
  'わかった！': ['Hiểu rồi!', 'Got it!', '알았어!'],
  'じょうず！': ['Giỏi lắm!', 'Well done!', '잘했어!'],
  'こんどは ほんとうに やってみよう！': ['Giờ mình chơi thật nhé!', "Now let's do it for real!", '이제 진짜로 해 보자!'],
  'きょうは たくさん がんばったね！': ['Hôm nay cố gắng nhiều rồi!', 'You worked hard today!', '오늘 정말 열심히 했어!'],
  'めを やすめて、つづきは また あした！': ['Cho mắt nghỉ ngơi, mai chơi tiếp nhé!', 'Rest your eyes, and more tomorrow!', '눈을 쉬게 하고 내일 또 하자!'],
  'もうすこし': ['Thêm chút nữa', 'A bit more', '조금 더'],
  'おしまい': ['Nghỉ thôi', 'Stop here', '그만할래'],

  // ---------------------------------------------------------------- the daily eye check
  'きょうの めチェック！ 5つの テストを するよ': ['Kiểm tra mắt hôm nay! Mình làm 5 bài nhé', "Today's eye check! We'll do 5 tests", '오늘의 눈 체크! 테스트 5개를 할 거야'],
  'きょうは もう チェック したよ。 れんしゅうで やってみよう': ['Hôm nay đã kiểm tra rồi. Chơi luyện tập nhé', "You've already checked today. Let's practise", '오늘은 이미 체크했어. 연습으로 해 보자'],
  'よく できました！ つぎは {name}': ['Giỏi lắm! Tiếp theo là {name}', 'Well done! Next is {name}', '잘했어! 다음은 {name}'],
  'めねんれいは {age}さい！': ['Tuổi mắt là {age}!', 'Your eye age is {age}!', '눈 나이는 {age}세!'],
  'きょうの めは {animal}！': ['Đôi mắt hôm nay là {animal}!', "Today's eyes: {animal}!", '오늘의 눈은 {animal}!'],
  '5つの テストで\nきょうの めを しらべるよ！': ['5 bài kiểm tra\nxem đôi mắt hôm nay thế nào!', '5 tests to see\nhow your eyes are today!', '5가지 테스트로\n오늘의 눈을 알아봐!'],
  'きょうは もう チェック したよ。\nれんしゅうで やってみよう！': ['Hôm nay đã kiểm tra rồi.\nChơi luyện tập nhé!', "You've already checked today.\nLet's practise!", '오늘은 이미 체크했어.\n연습으로 해 보자!'],
  'つぎは「{name}」だよ': ['Tiếp theo: “{name}”', 'Next: “{name}”', '다음은 「{name}」'],
  'うごき': ['Chuyển động', 'Motion', '움직임'],
  'いっしゅん': ['Nhìn nhanh', 'Flash', '순간'],
  'めの うごき': ['Đảo mắt', 'Eye moves', '눈 움직임'],
  'まわり': ['Xung quanh', 'Around', '주변'],
  'タッチ': ['Chạm', 'Tap', '터치'],
  'うごく ものを みるのが とくい だね！': ['Nhìn vật chuyển động là điểm mạnh nhé!', "You're good at watching moving things!", '움직이는 걸 보는 게 특기구나!'],
  'いっしゅんで みるのが とくい だね！': ['Nhìn trong chớp mắt là điểm mạnh nhé!', "You're good at seeing in a flash!", '한순간에 보는 게 특기구나!'],
  'めを うごかすのが とくい だね！': ['Đảo mắt thật nhanh là điểm mạnh nhé!', "You're good at moving your eyes!", '눈을 움직이는 게 특기구나!'],
  'まわりを みるのが とくい だね！': ['Nhìn xung quanh là điểm mạnh nhé!', "You're good at seeing all around!", '주변을 보는 게 특기구나!'],
  'みて すぐ タッチするのが とくい だね！': ['Nhìn rồi chạm thật nhanh là điểm mạnh nhé!', "You're good at seeing and tapping fast!", '보고 바로 터치하는 게 특기구나!'],
  'めねんれい <b>{age}</b> さい': ['Tuổi mắt <b>{age}</b>', 'Eye age <b>{age}</b>', '눈 나이 <b>{age}</b>세'],
  'きょうの めは<br><b>{animal}</b>': ['Đôi mắt hôm nay:<br><b>{animal}</b>', "Today's eyes:<br><b>{animal}</b>", '오늘의 눈은<br><b>{animal}</b>'],
  'おわる': ['Kết thúc', 'Finish', '끝내기'],
  'ぜんぶ すごいね！': ['Cái gì cũng giỏi!', 'Great at everything!', '다 대단해!'],
  '\n（れんしゅう なので きろくは しないよ）': ['\n(Luyện tập nên không ghi lại)', "\n(Just practice, so it isn't saved)", '\n(연습이라 기록하지 않아)'],

  // ---------------------------------------------------------------- the eye stretch
  'めの ストレッチ': ['Thể dục cho mắt', 'Eye Stretch', '눈 스트레칭'],
  'めの ストレッチ、はじめるよ！ ケロはかせと いっしょに やってみよう': ['Bắt đầu thể dục cho mắt nào! Cùng làm với Giáo sư Kero nhé', "Let's start the eye stretch! Do it together with Dr. Kero", '눈 스트레칭 시작! 케로 박사랑 같이 해 보자'],
  'がめんから めを はなして、まどの そとの とおくを みよう。20びょう、じっと みてね': ['Rời mắt khỏi màn hình, nhìn thật xa ra ngoài cửa sổ nhé. Nhìn yên 20 giây nhé', 'Look away from the screen, far out of the window. Keep looking for 20 seconds', '화면에서 눈을 떼고 창밖 먼 곳을 보자. 20초 동안 가만히 봐'],
  'はい、もどって きてね。つぎは まばたきを 3かい やろう': ['Được rồi, quay lại nào. Tiếp theo mình chớp mắt 3 lần nhé', "OK, come back! Now let's blink three times", '자, 돌아와. 다음은 눈 깜빡이기를 세 번 하자'],
  'そっと とじて': ['Nhắm nhẹ', 'Close gently', '살짝 감고'],
  'ぎゅっ': ['Nhắm chặt', 'Squeeze', '꼭'],
  'ぱっ！': ['Mở ra!', 'Open!', '번쩍!'],
  'かおは うごかさないで、めだけで ほしを ゆっくり おいかけてね。うえ と した': ['Giữ yên khuôn mặt, chỉ dùng mắt dõi theo ngôi sao thật chậm nhé. Lên và xuống', 'Keep your face still and slowly follow the star with just your eyes. Up and down', '얼굴은 움직이지 말고 눈으로만 별을 천천히 따라가. 위와 아래'],
  'みぎ と ひだり': ['Phải và trái', 'Right and left', '오른쪽과 왼쪽'],
  'ぐるっと まわして': ['Xoay một vòng', 'Round and round', '빙글빙글 돌려'],
  'めを とじて、10びょう やすもう': ['Nhắm mắt lại, nghỉ 10 giây nhé', 'Close your eyes and rest for 10 seconds', '눈을 감고 10초 쉬자'],
  'はい、めを あけて。おしまい！ めが すっきり したね': ['Mở mắt ra nào. Xong rồi! Mắt thấy dễ chịu hẳn nhỉ', 'Open your eyes. All done! Your eyes feel fresh!', '자, 눈을 떠. 끝! 눈이 개운해졌지'],

  // ---------------------------------------------------------------- the eye facts
  'めの まめちしき': ['Điều thú vị', 'Eye Facts', '눈 상식'],
  'まだ ひみつ': ['Vẫn còn bí mật', 'Still a secret', '아직 비밀'],
  'トレーニングを すると、1日に 1つ まめちしきが ふえるよ': ['Mỗi ngày luyện tập sẽ có thêm một điều thú vị mới', 'Each day you train, you get one new eye fact', '트레이닝을 하면 하루에 하나씩 눈 상식이 늘어나'],
  'めは いつも まばたきを して、めの おもてを きれいに して いるよ。1ぷんに 20かいくらい まばたき するんだって': ['Mắt luôn chớp để giữ cho mặt mắt sạch sẽ. Nghe nói mỗi phút mình chớp mắt khoảng 20 lần đó', 'Your eyes blink all the time to keep their surface clean. People blink about 20 times a minute!', '눈은 늘 깜빡여서 눈 표면을 깨끗하게 해. 1분에 20번쯤 깜빡인대'],
  'なみだには、めを ばいきんから まもる ちからが あるよ': ['Nước mắt giúp bảo vệ mắt khỏi vi khuẩn đó', 'Tears help protect your eyes from germs', '눈물에는 눈을 세균으로부터 지키는 힘이 있어'],
  'ねこの めの おくには、ひかりを はねかえす かがみのような ところが あるよ。だから くらくても よく みえるんだって': ['Trong mắt mèo có một lớp giống như tấm gương phản chiếu ánh sáng. Vì vậy mèo nhìn rõ cả khi trời tối', "At the back of a cat's eye there is a mirror-like layer that bounces light back. That's why cats see well in the dark", '고양이 눈 안쪽에는 빛을 되비추는 거울 같은 곳이 있어. 그래서 어두워도 잘 보인대'],
  'トンボの めは、ちいさな めが 1まんこ いじょう あつまって できて いるよ': ['Mắt chuồn chuồn được tạo thành từ hơn 10.000 con mắt nhỏ xíu', "A dragonfly's eyes are made of more than 10,000 tiny eyes", '잠자리 눈은 작은 눈이 1만 개 넘게 모여서 이루어져 있어'],
  'わしは とても めが いいよ。たかい そらから じめんの ちいさな どうぶつも みつけられるんだって': ['Đại bàng có đôi mắt rất tinh. Từ trên trời cao, nó nhìn thấy cả con vật nhỏ dưới đất', 'Eagles have very sharp eyes. From high in the sky they can spot small animals on the ground', '독수리는 눈이 아주 좋아. 높은 하늘에서 땅 위의 작은 동물도 찾을 수 있대'],
  'ふくろうは めを うごかせないから、くびを くるっと まわして みるんだよ': ['Cú mèo không đảo mắt được, nên nó xoay cả cái đầu để nhìn đó', "Owls can't move their eyes, so they turn their whole head to look around", '부엉이는 눈을 움직일 수 없어서 고개를 빙 돌려서 봐'],
  'もぐらは つちの なかで くらすから、めは とても ちいさいよ': ['Chuột chũi sống dưới đất nên mắt rất nhỏ', 'Moles live under the ground, so their eyes are very small', '두더지는 땅속에서 살아서 눈이 아주 작아'],
  'ちかくばかり みて いると めが つかれるよ。ときどき とおくを みようね': ['Nhìn gần mãi thì mắt sẽ mỏi. Thỉnh thoảng hãy nhìn ra xa nhé', 'Looking at close things for a long time tires your eyes. Look far away now and then', '가까운 것만 보면 눈이 피곤해져. 가끔 먼 곳을 보자'],
  'とおくの みどりを ながめると、めが ほっと するよ': ['Ngắm cây xanh ở xa giúp mắt thư giãn đó', 'Gazing at green trees far away helps your eyes relax', '멀리 있는 초록을 바라보면 눈이 편안해져'],
  'くらい ところで えほんを よむと めが つかれやすいよ。あかるい ところで よもうね': ['Đọc sách ở chỗ tối dễ bị mỏi mắt. Hãy đọc ở chỗ sáng nhé', 'Reading in the dark tires your eyes. Read where it is bright', '어두운 곳에서 그림책을 읽으면 눈이 쉽게 피곤해져. 밝은 곳에서 읽자'],
  'くろめの まんなかの「ひとみ」は、あかるいと ちいさく、くらいと おおきく なるよ。かがみで みて みよう': ['“Con ngươi” ở giữa mắt thu nhỏ khi sáng và to ra khi tối. Thử soi gương xem nhé', 'The “pupil” in the middle of your eye gets small in bright light and big in the dark. Try looking in a mirror', '까만 눈동자 가운데의 「동공」은 밝으면 작아지고 어두우면 커져. 거울로 봐 봐'],
  'まつげは、ほこりや ごみが めに はいらないように まもって くれるよ': ['Lông mi giúp ngăn bụi bẩn bay vào mắt', 'Eyelashes keep dust and dirt out of your eyes', '속눈썹은 먼지나 티끌이 눈에 들어가지 않게 지켜 줘'],
  'まゆげは、あせが めに はいらないように して くれるよ': ['Lông mày giúp mồ hôi không chảy vào mắt', 'Eyebrows stop sweat from running into your eyes', '눈썹은 땀이 눈에 들어가지 않게 해 줘'],
  'みぎめと ひだりめは すこし ちがう ばしょから みて いるよ。だから ものの とおさが わかるんだって': ['Mắt phải và mắt trái nhìn từ hai chỗ hơi khác nhau. Nhờ vậy mình biết đồ vật ở xa hay gần', 'Your right and left eyes look from slightly different places. That is how you can tell how far away things are', '오른쪽 눈과 왼쪽 눈은 조금 다른 곳에서 보고 있어. 그래서 물건이 얼마나 먼지 알 수 있대'],
  'かたほうの めを てで かくして ゆびを みて みよう。かくす めを かえると ゆびが うごいて みえるよ': ['Lấy tay che một mắt rồi nhìn ngón tay. Đổi mắt che, ngón tay như dịch chuyển đó', 'Cover one eye with your hand and look at your finger. Switch eyes, and the finger seems to jump!', '한쪽 눈을 손으로 가리고 손가락을 봐 봐. 가리는 눈을 바꾸면 손가락이 움직여 보여'],
  'うさぎの めは かおの よこに ついて いるから、うしろの ほうまで みえるよ': ['Mắt thỏ nằm ở hai bên đầu, nên thỏ nhìn được cả phía sau', "A rabbit's eyes are on the sides of its head, so it can see almost behind itself", '토끼 눈은 얼굴 옆에 있어서 뒤쪽까지 보여'],
  'タコや イカにも めが あるよ。とても よく みえるんだって': ['Bạch tuộc và mực cũng có mắt. Nghe nói chúng nhìn rất rõ', 'Octopuses and squid have eyes too, and they see very well', '문어나 오징어에게도 눈이 있어. 아주 잘 보인대'],
  'ヘビの なかまには、あたたかい ものを かんじる あなを もつ ものが いるよ。くらくても えものが わかるんだって': ['Có loài rắn có những cái lỗ cảm nhận được hơi ấm. Nhờ vậy trời tối vẫn biết con mồi ở đâu', 'Some snakes have little pits that feel warmth, so they can find their food even in the dark', '어떤 뱀은 따뜻한 걸 느끼는 구멍이 있어. 어두워도 먹이를 알 수 있대'],
  'うまの めは とても おおきくて、ほとんど ぐるっと まわりが みえるよ': ['Mắt ngựa rất to, nhìn được gần hết một vòng xung quanh', "A horse's eyes are very big, and it can see almost all the way around", '말의 눈은 아주 커서 거의 빙 둘러 다 보여'],
  'めを ぎゅっと つぶって ぱっと ひらくと、めの まわりの たいそうに なるよ': ['Nhắm chặt mắt rồi mở bừng ra là một bài tập cho vùng quanh mắt đó', 'Squeezing your eyes shut and popping them open exercises the muscles around your eyes', '눈을 꼭 감았다가 번쩍 뜨면 눈 주위 체조가 돼'],
  'テレビや タブレットは、はなれて みようね。ちかすぎると めが つかれるよ': ['Xem tivi hay máy tính bảng thì ngồi xa ra nhé. Gần quá mắt sẽ mỏi', 'Watch TV and tablets from a distance. Too close tires your eyes', 'TV나 태블릿은 떨어져서 보자. 너무 가까우면 눈이 피곤해'],
  'がめんを ずっと みたら、ときどき めを やすめようね': ['Nhìn màn hình lâu rồi thì thỉnh thoảng cho mắt nghỉ nhé', 'After looking at a screen for a long time, rest your eyes now and then', '화면을 오래 봤으면 가끔 눈을 쉬게 하자'],
  'そとで あそぶ ことは、めに いいと いわれて いるよ': ['Người ta nói chơi ngoài trời rất tốt cho mắt', 'Playing outside is said to be good for your eyes', '밖에서 노는 건 눈에 좋다고 해'],
  'ひとの めには、いろを みわける ための 3しゅるいの センサーが あるよ。あか・みどり・あお だよ': ['Mắt người có 3 loại cảm biến để phân biệt màu: đỏ, xanh lá và xanh dương', 'Your eyes have 3 kinds of sensors for telling colours apart: red, green and blue', '사람 눈에는 색을 구별하는 3가지 센서가 있어. 빨강·초록·파랑이야'],
  'ミツバチには、ひとには みえない ひかりが みえるんだって': ['Nghe nói ong mật nhìn thấy cả loại ánh sáng mà người không thấy được', 'Honeybees can see a kind of light that people cannot', '꿀벌은 사람에게 안 보이는 빛이 보인대'],
  'いぬは いろの みえかたが ひとと ちがって、あかと みどりが にて みえるんだって': ['Chó nhìn màu khác với người. Với chó, màu đỏ và màu xanh lá trông gần giống nhau', 'Dogs see colours differently from people: red and green look alike to them', '강아지는 색이 사람과 다르게 보여서 빨강과 초록이 비슷해 보인대'],
  'めの いろ（くろ・ちゃいろ・あお など）は、ひとみの まわりの「こうさい」の いろ だよ': ['Màu mắt (đen, nâu, xanh…) là màu của “mống mắt” bao quanh con ngươi', 'The colour of your eyes (black, brown, blue…) is the colour of the “iris” around the pupil', '눈 색깔(검정·갈색·파랑 등)은 눈동자 주위 「홍채」의 색이야'],
  'あかちゃんは うまれた ときは あまり よく みえないよ。だんだん みえるように なるんだって': ['Em bé mới sinh chưa nhìn rõ lắm. Rồi dần dần sẽ nhìn rõ hơn', "Newborn babies can't see very well. Their eyes get better little by little", '아기는 태어났을 때 잘 안 보여. 점점 보이게 된대'],
  'ボールを さいごまで よく みると、じょうずに キャッチ できるよ': ['Nhìn quả bóng thật kỹ đến cuối cùng thì sẽ bắt bóng giỏi đó', 'Watch the ball all the way, and you will catch it well', '공을 끝까지 잘 보면 잘 잡을 수 있어'],
  'うごいて いる ものを はっきり みる ちからを「どうたいしりょく」と いうよ。スポーツで だいかつやく！': ['Khả năng nhìn rõ vật đang chuyển động gọi là “thị lực động”. Rất có ích khi chơi thể thao!', 'Seeing moving things clearly is called “dynamic vision”. It is a big help in sports!', '움직이는 걸 또렷이 보는 힘을 「동체 시력」이라고 해. 스포츠에서 대활약!'],
  'いっしゅんで たくさんの ものを みる ちからを「しゅんかんし」と いうよ': ['Khả năng nhìn được nhiều thứ trong chớp mắt gọi là “nhìn tức thời”', 'Seeing lots of things in a flash is called “instant vision”', '한순간에 많은 걸 보는 힘을 「순간 시력」이라고 해'],
  'まえを みたまま、まわりの ものに きづく ちからを「しゅうへんしや」と いうよ': ['Khả năng vừa nhìn phía trước vừa nhận ra đồ vật xung quanh gọi là “tầm nhìn ngoại vi”', 'Noticing things around you while looking ahead is called “peripheral vision”', '앞을 보면서 주변의 것을 알아차리는 힘을 「주변 시야」라고 해'],
  'めで みて すぐに てを うごかす ちからを「めと ての きょうおう」と いうよ': ['Khả năng nhìn rồi cử động tay ngay gọi là “phối hợp mắt và tay”', 'Seeing something and moving your hands right away is called “eye-hand coordination”', '눈으로 보고 바로 손을 움직이는 힘을 「눈과 손의 협응」이라고 해'],
  'めを すばやく うごかす ちからを「がんきゅう うんどう」と いうよ。えほんを よむ ときにも つかうよ': ['Khả năng đảo mắt thật nhanh gọi là “vận động nhãn cầu”. Mình dùng nó cả khi đọc sách đó', 'Moving your eyes quickly is called “eye movement”. You use it when you read books, too', '눈을 빠르게 움직이는 힘을 「안구 운동」이라고 해. 그림책을 읽을 때도 써'],
  'シマウマの しましまは、たくさん あつまると 1とうずつ みわけにくく なると いわれて いるよ': ['Người ta nói khi ngựa vằn đứng thành đàn, những sọc vằn làm khó nhận ra từng con một', 'When lots of zebras stand together, their stripes make it hard to pick out just one', '얼룩말 줄무늬는 많이 모이면 한 마리씩 알아보기 어려워진다고 해'],
  'まっくらな へやでも、しばらく すると だんだん みえて くるよ。めが くらさに なれるんだって': ['Dù phòng tối om, đợi một lúc sẽ dần dần nhìn thấy. Đó là vì mắt đã quen với bóng tối', 'Even in a dark room, you start to see after a while. Your eyes get used to the dark', '깜깜한 방에서도 조금 지나면 점점 보여. 눈이 어둠에 익숙해지는 거래'],
  'めは みた ものを「のう」に おくって いるよ。ものを みるのは、めと のうの チームプレー なんだ': ['Mắt gửi những gì nhìn thấy lên “não”. Nhìn là sự phối hợp giữa mắt và não đó', 'Your eyes send what they see to your “brain”. Seeing is teamwork between eyes and brain', '눈은 본 것을 「뇌」로 보내. 보는 건 눈과 뇌의 팀플레이야'],
  'ゆうがた くらく なると、いろが みわけにくく なるよ': ['Khi trời chạng vạng tối, màu sắc khó phân biệt hơn', 'When it gets dark in the evening, colours are harder to tell apart', '저녁에 어두워지면 색을 구별하기 어려워져'],
  'あくびを すると なみだが でるのは、めの まわりが ぎゅっと うごくから だと いわれて いるよ': ['Người ta nói ngáp thì chảy nước mắt là vì vùng quanh mắt bị ép lại', 'They say yawning brings tears because the muscles around your eyes squeeze', '하품하면 눈물이 나는 건 눈 주위가 꽉 움직이기 때문이래'],
  'めを こすると ばいきんが はいる ことが あるよ。かゆい ときは おうちの ひとに いおうね': ['Dụi mắt có thể làm vi khuẩn vào mắt. Khi ngứa mắt thì nói với bố mẹ nhé', 'Rubbing your eyes can let germs in. If they itch, tell a grown-up', '눈을 비비면 세균이 들어갈 수 있어. 가려울 땐 가족에게 말하자'],
  'サングラスは、まぶしい ひかりから めを まもって くれるよ': ['Kính râm bảo vệ mắt khỏi ánh sáng chói', 'Sunglasses protect your eyes from bright light', '선글라스는 눈부신 빛으로부터 눈을 지켜 줘'],
  'ぼうしの つばも、まぶしい ひかりから めを まもって くれるよ': ['Vành mũ cũng bảo vệ mắt khỏi ánh sáng chói', 'The brim of a hat also protects your eyes from bright light', '모자 챙도 눈부신 빛으로부터 눈을 지켜 줘'],
  'おひさまを ちょくせつ みては いけないよ。めが いたく なって しまうよ': ['Không được nhìn thẳng vào mặt trời nhé. Mắt sẽ bị đau đó', 'Never look straight at the sun. It hurts your eyes', '해를 직접 보면 안 돼. 눈이 아파져'],
  'やさいや さかなを しっかり たべると、めの げんきにも いいと いわれて いるよ': ['Người ta nói ăn nhiều rau và cá cũng tốt cho mắt', 'Eating plenty of vegetables and fish is said to be good for your eyes', '채소나 생선을 잘 먹으면 눈 건강에도 좋다고 해'],
  'よる しっかり ねむると、めも ゆっくり やすめるよ': ['Ngủ ngon vào ban đêm thì mắt cũng được nghỉ ngơi thật tốt', 'When you sleep well at night, your eyes get a good rest too', '밤에 푹 자면 눈도 푹 쉴 수 있어'],
  'ハチには おおきな めが 2つと、ちいさな めが 3つ あるんだって': ['Nghe nói con ong có 2 mắt to và 3 mắt nhỏ', 'Bees have 2 big eyes and 3 little ones', '벌에게는 큰 눈 2개와 작은 눈 3개가 있대'],
  'めの たいそうを まいにち すると、めを うごかすのが じょうずに なるよ。いっしょに がんばろうね！': ['Tập thể dục cho mắt mỗi ngày sẽ giúp đảo mắt giỏi hơn. Cùng cố gắng nhé!', "Do eye exercises every day and you'll get better at moving your eyes. Let's keep going together!", '눈 체조를 매일 하면 눈을 움직이는 게 능숙해져. 같이 힘내자!'],

  // ---------------------------------------------------------------- stamps and records
  '{y}ねん {m}がつ': ['Tháng {m} năm {y}', '{mon} {y}', '{y}년 {m}월'],
  'あと <b>{n}こ</b> で<br>「{name}」が ふえるよ！': ['Thêm <b>{n}</b> con dấu nữa<br>là có “{name}”!', '<b>{n}</b> more stamps<br>and “{name}” opens!', '<b>{n}개</b> 더 모으면<br>「{name}」가 생겨!'],
  'ぜんぶ あいたよ！ まいにち つづけて<br>はなまるを あつめよう！': ['Mở hết rồi! Chơi đều mỗi ngày<br>để sưu tầm dấu bông hoa nhé!', 'Everything is open! Keep playing<br>every day to collect flower stamps!', '전부 열렸어! 매일 계속해서<br>꽃 도장을 모으자!'],
  'まだ だよ': ['Chưa có', 'Not yet', '아직이야'],
  '{n}かい': ['{n} lần', '{n}', '{n}번'],
  'まだ きろくが ないよ': ['Chưa có kỷ lục', 'No records yet', '아직 기록이 없어'],
  'いちばん いい きろく：{best}': ['Kỷ lục tốt nhất: {best}', 'Best record: {best}', '최고 기록: {best}'],
  'あそんだ かず：{n}かい': ['Số lần chơi: {n}', 'Times played: {n}', '해 본 횟수: {n}번'],

  // ---------------------------------------------------------------- shop
  'ケロちゃん': ['Kero', 'Kero', '케로'],
  'ミミちゃん': ['Mimi', 'Mimi', '미미'],
  'ニャーちゃん': ['Meo Meo', 'Meow', '야옹이'],
  'ワンちゃん': ['Gâu Gâu', 'Woof', '멍멍이'],
  '★を つかって おともだちを ふやそう！': ['Dùng ★ để có thêm bạn mới nhé!', 'Use your ★ to make new friends!', '★로 새 친구를 만들자!'],
  'つかってる': ['Đang chọn', 'Chosen', '함께하는 중'],
  'えらぶ': ['Chọn', 'Choose', '고르기'],
  '{star}{price} で かう': ['Mua {star}{price}', 'Buy {star}{price}', '{star}{price}에 사기'],
  'あと ★{n} で かえるよ': ['Cần thêm ★{n} nữa là mua được', '{n} more ★ to buy it', '★{n}개만 더 모으면 살 수 있어'],
  '{name}を<br>{star}{price} で かう？': ['Mua {name}<br>với {star}{price} nhé?', 'Buy {name}<br>for {star}{price}?', '{name}를<br>{star}{price}에 살까?'],
  '{name}が なかまに なったよ！': ['{name} đã thành bạn rồi!', '{name} is your friend now!', '{name}가 친구가 되었어!'],
  'かう': ['Mua', 'Buy', '살래'],

  // ---------------------------------------------------------------- grown-ups (family mode, admin)
  '管理者パスワード': ['Mật khẩu quản lý', 'Admin password', '관리자 비밀번호'],
  '閉じる': ['Đóng', 'Close', '닫기'],
  '管理者メニュー': ['Menu quản lý', 'Admin menu', '관리자 메뉴'],
  'ユーザー（かぞくモード）': ['Người chơi (chế độ gia đình)', 'Players (family mode)', '사용자 (가족 모드)'],
  'ユーザー': ['Người chơi', 'Players', '사용자'],
  'ケロちゃん ランドと ぜんぶの ゲームで おなじ ユーザーだよ': ['Người chơi dùng chung cho Thế giới Kero và mọi trò chơi', 'The same players in Kero Land and every game', '케로 랜드와 모든 게임에서 같은 사용자예요'],
  'ユーザーを ふやす': ['Thêm người chơi', 'Add a player', '사용자 추가'],
  'ユーザーの せってい': ['Cài đặt người chơi', 'Player settings', '사용자 설정'],
  'なまえ': ['Tên', 'Name', '이름'],
  'れい：はなこ': ['Ví dụ: Na', 'e.g. Hana', '예: 하나'],
  'へんしゅう': ['Sửa', 'Edit', '편집'],
  'もう一度で けす': ['Nhấn lần nữa để xóa', 'Tap again to delete', '한 번 더 누르면 삭제'],
  'いまの ユーザー：{name}（{type}）<br>スタンプ {s}　あつめた★ {a}　つかった★ {b}': ['Người chơi: {name} ({type})<br>Con dấu {s}　★ đã nhặt {a}　★ đã dùng {b}', 'Player: {name} ({type})<br>Stamps {s}　★ collected {a}　★ spent {b}', '지금 사용자: {name} ({type})<br>도장 {s}　모은 ★ {a}　쓴 ★ {b}'],
  '全トレーニング解放：{v}': ['Mở mọi bài luyện: {v}', 'Unlock all trainings: {v}', '모든 트레이닝 열기: {v}'],
  'オン': ['Bật', 'On', '켬'],
  'オフ': ['Tắt', 'Off', '끔'],
  'おしまいの声かけ：{v}': ['Nhắc nghỉ: {v}', 'Time-to-stop reminder: {v}', '그만하기 알림: {v}'],
  '{n}つで': ['sau {n} bài', 'after {n}', '{n}개 후'],
  'しない': ['Không', 'Off', '안 함'],
  'このユーザーの記録をリセット': ['Xóa kỷ lục của người chơi này', "Reset this player's records", '이 사용자 기록 초기화'],
  'もう一度押すと消えます': ['Nhấn lần nữa để xóa', 'Press again to erase', '한 번 더 누르면 지워져요'],
  'ケロはかせの こえ：{credit}。': ['Giọng Giáo sư Kero: {credit}. ', "Dr. Kero's voice: {credit}. ", '케로 박사 목소리: {credit}. '],
  '日本語の こえ：{credit}。': ['Giọng tiếng Nhật: {credit}. ', 'Japanese voice: {credit}. ', '일본어 목소리: {credit}. '],
  'パソコンでの確認中は 音も声も出しません（アドレスに ?sound=1 を付けると出ます）。': ['Khi kiểm tra trên máy tính, trò chơi không phát âm thanh hay giọng nói (thêm ?sound=1 vào địa chỉ để bật).', 'While testing on a computer there is no sound or voice (add ?sound=1 to the address to hear it).', '컴퓨터에서 확인할 때는 소리도 목소리도 나오지 않아요 (주소에 ?sound=1을 붙이면 나와요).'],
  'この ことばの こえ：スマホの 読み上げの 声が 見つかりました。': ['Giọng tiếng Việt: đã tìm thấy giọng đọc trên điện thoại.', "English voice: the phone's text-to-speech voice was found.", '한국어 목소리: 휴대폰의 음성 읽기 목소리를 찾았어요.'],
  'この ことばの こえ：スマホに 声が 見つかりません。Android の「設定 → システム → 言語と入力 → テキスト読み上げ」で この ことばの 音声データを 入れると しゃべります。': ['Giọng tiếng Việt: chưa tìm thấy giọng đọc trên điện thoại. Vào “Cài đặt → Hệ thống → Ngôn ngữ và phương thức nhập → Chuyển văn bản thành giọng nói” của Android, tải dữ liệu giọng tiếng Việt thì Giáo sư Kero sẽ nói.', 'English voice: no voice was found on the phone. Install the English voice data in Android “Settings → System → Languages & input → Text-to-speech output” and Dr. Kero will talk.', '한국어 목소리: 휴대폰에서 목소리를 찾지 못했어요. Android의 “설정 → 시스템 → 언어 및 입력 → 텍스트 음성 변환”에서 한국어 음성 데이터를 설치하면 말해요.'],
  'この ことばの こえ：このブラウザでは 使えません。': ['Giọng tiếng Việt: trình duyệt này không hỗ trợ.', "English voice: this browser can't speak.", '한국어 목소리: 이 브라우저에서는 쓸 수 없어요.']
});

// The big title, one line per row (each letter hops on its own).
var GAME_LOGO = { ja: ['ケロちゃん', 'みるみる'], vi: ['Kero', 'Mắt Tinh'], en: ['Kero', 'Quick Eyes'], ko: ['케로', '반짝눈'] };

// The days on the stamp calendar (Sunday first).
var MIRU_WEEK = {
  vi: ['CN', 'T2', 'T3', 'T4', 'T5', 'T6', 'T7'],
  en: ['Su', 'Mo', 'Tu', 'We', 'Th', 'Fr', 'Sa'],
  ko: ['일', '월', '화', '수', '목', '금', '토']
};
